#!/bin/bash

TZ=${TZ:-Etc/UTC}

PUID=${PUID:-0}
PGID=${PGID:-0}

VRisingHost_Name=${VRisingHost_Name:-"\"Syter VRising Server\""}
VRisingHost_SaveName=${VRisingHost_SaveName:-"\"world1\""}
VRisingHost_Port=${VRisingHost_Port:-27015}
VRisingHost_QueryPort=${VRisingHost_QueryPort:-27016}

AdminList_Ids=${AdminList_Ids:-}