version: "3.1"
services: 
  vrising-server:
    container_name: vrising-server
    image: syter/vrising-docker:latest
    environment:
      #General
      - TZ=Europe/Lisbon
      - AdminList_Ids=steamid1 steamid2
      #Host Settings
      - VRisingHost_GameSettingsPreset="Level70PvE"
      - VRisingHost_Password="changeme"
      - VRisingHost_Rcon_Enabled=true
      - VRisingHost_Rcon_Password="changeme"
      #Game Settings
      - VRisingGame_ClanSize=10
      #BepInEx
      - Mod_BepInEx_Name=BepInExPack_V_Rising
      - Mod_BepInEx_Namespace=BepInEx
      - Mod_BepInEx_Source=/BepInExPack_V_Rising/
      - Mod_BepInEx_Destination=/
      #Wetstone
      - Mod_Wetstone_Name=Wetstone
      - Mod_Wetstone_Namespace=molenzwiebel
      - Mod_Wetstone_Source=/
      - Mod_Wetstone_Destination=/BepInEx/plugins/Wetstone
      #QuickStash
      - Mod_QuickStash_Name=QuickStash
      - Mod_QuickStash_Namespace=Elmegaard
      - Mod_QuickStash_Source=/
      - Mod_QuickStash_Destination=/BepInEx/WetstonePlugins
      #ChatCommands
      - Mod_ChatCommands_Name=ChatCommands
      - Mod_ChatCommands_Namespace=Nopey
      - Mod_ChatCommands_Source=/
      - Mod_ChatCommands_Destination=/BepInEx/WetstonePlugins
    volumes: 
      - vrising-server:/mnt/vrising/server
      - vrising-data:/mnt/vrising/data
    ports: 
      - "27015:27015/udp"
      - "27016:27016/udp"
    restart: unless-stopped
volumes:
  vrising-server:
    external: false
  vrising-data:
    external: false