version: "3.1"
services: 
  vrising:
    container_name: vrising-server
    image: syter/vrising-docker:latest
    environment:
      - TZ=Europe/Lisbon
      - ServerName=SyteRVRisingServer
      - VRisingHost_Name="SyTeR VRising Server"
      - VRisingHost_Port=27015
      - VRisingHost_QueryPort=27016
    volumes: 
      - vrising-server:/mnt/vrising/server
      - vrising-data:/mnt/vrising/data
    ports: 
      - "27015:27015/udp"
      - "27016:27016/udp"
    restart: unless-stopped
volumes:
  vrising-server:
    external: false
  vrising-data:
    external: false