#!/bin/bash

. /usr/local/etc/vrising/defaults
. /usr/local/etc/vrising/common

main() {
  debug "Starting main of entrypoint"
  start_wine
  apply_permissions
  configure_timezone
  install_server
  handleHostSettings
  handleGameSettings
  write_adminlist
  handle_mods
  startServer
}

startServer() {
  local host_port=" -gamePort $VRisingHost_Port"
  local host_query_port=" -queryPort $VRisingHost_QueryPort"

  info "Starting V Rising Dedicated Server with name $ServerName"
  Xvfb :0 -screen 0 1024x768x16 & \
  sleep 5
  DISPLAY=:0.0 WINEDLLOVERRIDES="winhttp=n,b" wine "Z:$server_path/VRisingServer.exe" -persistentDataPath $data_path -serverName "$ServerName" -saveName "$WorldName" -logFile "Z:$data_path/VRisingServer.log" "$host_port" "$host_query_port"
  /usr/bin/tail -f "$data_path/VRisingServer.log"
}

main